name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python & Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: app/environment.yml
          activate-environment: v-pipe-scout-app
          auto-activate-base: false

      - name: Ensure config.yaml is available
        run: cp app/config.yaml app/config.yaml

      - name: Debug - list files
        run: ls -R  

      - name: Testing â€“ Smoke & Unit Tests
        run: conda run -n v-pipe-scout-app pytest app
        env:
          PYTHONPATH: ${{ github.workspace }}
          APP_PATH: app/app.py