name: Worker Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-worker:
    name: Test Worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python & Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: worker/environment.yml
          activate-environment: v-pipe-scout-worker
          auto-activate-base: false

      - name: Unit Tests
        run: conda run -n v-pipe-scout-worker pytest
        working-directory: ./worker
        env:
          PYTHONPATH: ${{ github.workspace }}